name: Guard: Open issue on failure
on:
  workflow_run:
    workflows:
      - Cancel Test
      - Append Index (Manual)
      - Append Index (UTC hourly)
    types: [completed]
permissions:
  actions: read
  contents: read
  issues: write
jobs:
  open_issue_on_failure:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Write summary
        run: |
          echo
            Run: ${{ github.event.workflow_run.html_url }} >> $GITHUBSTEP_SUMMARY
      - name: Open issue on failure
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const title = `[guard][auto] ${run.name} failed: #${run.run_number} (${run.conclusion})`
            const body = [
              `Run: ${run.html_url}`,
              `Workflow: ${run.name}`,
              `Event: ${run.event}`,
              `Conclusion: ${run.conclusion}`,
              `Started: ${run.run_started_at}`,
              `Updated: ${run.updated_at}`
            ].join('\n\n');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['guard', 'auto']
            });